version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ImageUploadDB=Host=my_postgres_container;Port=5432;Username=postgres;Password=30032005bvi;Database=imageuploaddb
    volumes:
      - ./wwwroot/images:/app/wwwroot/images
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
