services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ImageUploadDB=Server=sqlserver-container;Database=ImageUploadDB;User Id=SA;Password=YourStrong!Password;TrustServerCertificate=True;
    volumes:
      - C:\Users\bvivl\source\repos\ImageUploadService\ImageUploadService\wwwroot\images:/app/wwwroot/images  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
