    version: '3.8'

    services:
      rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-container
        ports:
          - "5672:5672"   # Порт для клієнтських підключень
          - "15672:15672" # Порт для веб-інтерфейсу RabbitMQ
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        networks:
          - app-network

      web:
        build: .
        container_name: web-service
        ports:
          - "5000:5000"
        environment:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionStrings__ImageUploadDB: Host=postgres-container;Port=5432;Username=postgres;Password=30032005bvi;Database=imageuploaddb;
          RabbitMQ__HostName: rabbitmq-container
          RabbitMQ__UserName: guest
          RabbitMQ__Password: guest
        volumes:
          - ./wwwroot:/app/wwwroot  
        networks:
          - app-network
        depends_on:
          - rabbitmq

      postgres:
        image: postgres:17
        container_name: postgres-container
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 30032005bvi
          POSTGRES_DB: imageuploaddb
        ports:
          - "5432:5432"
        volumes:
          - postgres-data:/var/lib/postgresql/data
        networks:
          - app-network

    networks:
      app-network:
        driver: bridge

    volumes:
      postgres-data:
